steps:

- name: 'ubuntu'
  env:
  - 'BUILD=$BUILD_ID'

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/dreamhome-cpo/dhnotification:$BUILD_ID', '.']
  id: 'build-image'

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/dreamhome-cpo/dhnotification:$BUILD_ID']
  waitFor: ['build-image']
  id: 'push-image'

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['components', 'install', 'kubectl']
  waitFor: ['push-image']
  id: 'install-kubectl'

- name: 'ubuntu'
  args: ['sh', '-c', 'kubectl set image deployment/dhnotification dhnotification=gcr.io/dreamhome-cpo/dhnotification:$BUILD_ID --namespace dreamhome']
  waitFor: ['install-kubectl']

images: ['gcr.io/dreamhome-cpo/dhnotification']

